//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instructor()
        {
            this.Disciplinas = new HashSet<Disciplinas>();
        }
    
        public string ID_Instructor { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Correo { get; set; }
        public string Contraseña { get; set; }
        public string Telefono { get; set; }
        public string TelefonoEmergencia { get; set; }
        public int Edad { get; set; }
        public string CondicionesMedicas { get; set; }
        public string Direccion { get; set; }
        public string Rol { get; set; }
        public int ID_Especialidad { get; set; }
        public int ID_Administrador { get; set; }
        public int ID_Sexo { get; set; }
        public int ID_TipoSangre { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disciplinas> Disciplinas { get; set; }
        public virtual Disciplinas Disciplinas1 { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual TipoSangre TipoSangre { get; set; }

        public string nombreDis { get; set; }

        public string nombreAdm { get; set; }
    }
}
