//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public string ID_Instructor { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Correo { get; set; }
        public string Contraseña { get; set; }
        public string ID_Especialidad { get; set; }
        public string ID_Administrador { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Especialidad Especialidad { get; set; }
    }
}
