//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProyectoEntities : DbContext
    {
        public ProyectoEntities()
            : base("name=ProyectoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Disciplinas> Disciplinas { get; set; }
        public virtual DbSet<HorariosDisciplinas> HorariosDisciplinas { get; set; }
    
        public virtual int InsertarClientes(string pIdCliente, string pNombre, string pPrimerApellido, string pSegundoApellido, string pCorreo, Nullable<int> pEdad, string pContraseña, string pDireccion, string pTelefono, string pTelefonoEmergencia, Nullable<decimal> pPeso, Nullable<decimal> pEstatura, string pCondicionesMedicas, string pTipoSangre)
        {
            var pIdClienteParameter = pIdCliente != null ?
                new ObjectParameter("pIdCliente", pIdCliente) :
                new ObjectParameter("pIdCliente", typeof(string));
    
            var pNombreParameter = pNombre != null ?
                new ObjectParameter("pNombre", pNombre) :
                new ObjectParameter("pNombre", typeof(string));
    
            var pPrimerApellidoParameter = pPrimerApellido != null ?
                new ObjectParameter("pPrimerApellido", pPrimerApellido) :
                new ObjectParameter("pPrimerApellido", typeof(string));
    
            var pSegundoApellidoParameter = pSegundoApellido != null ?
                new ObjectParameter("pSegundoApellido", pSegundoApellido) :
                new ObjectParameter("pSegundoApellido", typeof(string));
    
            var pCorreoParameter = pCorreo != null ?
                new ObjectParameter("pCorreo", pCorreo) :
                new ObjectParameter("pCorreo", typeof(string));
    
            var pEdadParameter = pEdad.HasValue ?
                new ObjectParameter("pEdad", pEdad) :
                new ObjectParameter("pEdad", typeof(int));
    
            var pContraseñaParameter = pContraseña != null ?
                new ObjectParameter("pContraseña", pContraseña) :
                new ObjectParameter("pContraseña", typeof(string));
    
            var pDireccionParameter = pDireccion != null ?
                new ObjectParameter("pDireccion", pDireccion) :
                new ObjectParameter("pDireccion", typeof(string));
    
            var pTelefonoParameter = pTelefono != null ?
                new ObjectParameter("pTelefono", pTelefono) :
                new ObjectParameter("pTelefono", typeof(string));
    
            var pTelefonoEmergenciaParameter = pTelefonoEmergencia != null ?
                new ObjectParameter("pTelefonoEmergencia", pTelefonoEmergencia) :
                new ObjectParameter("pTelefonoEmergencia", typeof(string));
    
            var pPesoParameter = pPeso.HasValue ?
                new ObjectParameter("pPeso", pPeso) :
                new ObjectParameter("pPeso", typeof(decimal));
    
            var pEstaturaParameter = pEstatura.HasValue ?
                new ObjectParameter("pEstatura", pEstatura) :
                new ObjectParameter("pEstatura", typeof(decimal));
    
            var pCondicionesMedicasParameter = pCondicionesMedicas != null ?
                new ObjectParameter("pCondicionesMedicas", pCondicionesMedicas) :
                new ObjectParameter("pCondicionesMedicas", typeof(string));
    
            var pTipoSangreParameter = pTipoSangre != null ?
                new ObjectParameter("pTipoSangre", pTipoSangre) :
                new ObjectParameter("pTipoSangre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarClientes", pIdClienteParameter, pNombreParameter, pPrimerApellidoParameter, pSegundoApellidoParameter, pCorreoParameter, pEdadParameter, pContraseñaParameter, pDireccionParameter, pTelefonoParameter, pTelefonoEmergenciaParameter, pPesoParameter, pEstaturaParameter, pCondicionesMedicasParameter, pTipoSangreParameter);
        }
    }
}
