//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int reservaID { get; set; }
        public int claseID { get; set; }
        public System.DateTime dia { get; set; }
        public System.TimeSpan hora { get; set; }
        public bool equipo { get; set; }
        public string ID_Cliente { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Disciplinas Disciplinas { get; set; }
        public string nombreDis { get; set; }
    }
}
