//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutinas
    {
        public int ID_Ejercicio { get; set; }
        public string NomEjercicio { get; set; }
        public decimal Duracion { get; set; }
        public int Series { get; set; }
        public string Repeticion { get; set; }
        public string Descanso { get; set; }
    }
}
