//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutinas
    {
        public int ID_Ejercicio { get; set; }
        public string NomEjercicio { get; set; }
        public decimal Duracion { get; set; }
        public int Series { get; set; }
        public string Repeticion { get; set; }
        public string Descanso { get; set; }
    }
}
